name: !!str cvar-langevin
cvar:
  delta: !!float 1e-2 # (1-delta) is the quantile parameter in CVaR
  gamma: !!float 1e-2 # smoothing parameter in CVaR

langevin_sampler:
  temperature: !!float 1e-3 # diffusion coefficient
  step_size: !!float 5e-1 # resolution of time discretization
  number_of_steps: !!int 20000 # number of Langevin steps
  batch_size: !!int 2000

upper_level_optimizer:
  optimzer: !!str SGD
  step_size: !!float 1e-2 # stepsize for minimizing beta in CVaR
  momentum: !!float .9 # momentum for minimizing theta in BLO
  

