name: !!str cvar-langevin
cvar:
  delta: !!float 1e-2 # (1-delta) is the quantile parameter in CVaR
  gamma: !!float 1e-2 # smoothing parameter in CVaR

langevin_sampler:
  temperature: !!float 1e-3 # diffusion coefficient
  step_size: !!float 1e-1 # resolution of time discretization
  number_of_steps: !!int 50000 # number of Langevin steps
  batch_size: !!int 5000

upper_level_optimizer:
  optimzer: !!str SGD
  step_size: !!float 1e-2 # stepsize for minimizing theta in upper-level problem
  momentum: !!float 0. # momentum for minimizing theta in BLO

beta_optimizer:
  optimzer: !!str SGD
  step_size: !!float 1e-3 # stepsize for minimizing beta in CVaR
  number_of_steps: !!int 10000 # number of GD steps for beta

